server:
  port: 8081
  max-http-request-header-size: 16384

spring:
  ai:
    deepseek:
      api-key: sk-c2f36f37e70a487c95ffbcd91511c326
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:0.6b
          temperature: 0.7
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas
      api-key: ee6d3290fe29481b85eb896240a4dcf8.1NECfM3ru0bNGrGX
      chat:
        options:
          model: glm-4-air
          temperature: 0.7
    openai:
#      base-url: https://api.zhizengzeng.com/v1
#      api-key: sk-zk25a23f0a77661256c03586862d886a2b569118cbc5a72a
#      chat:
#        options:
#          model: gpt-4o
#          temperature: 0.7
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: sk-0d5552c26ffe4778a6eec6164781cd12
        chat:
          options:
            model: qwen-turbo
            temperature: 0.7

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug